[features]
seeds = false
[programs.localnet]
switchboard_vrf_flip = "4TXz5v1tmgSXBWBVQfv67Fj6GwkL4vzw85M5hifPAE6M"
[programs.devnet]
switchboard_vrf_flip = "4TXz5v1tmgSXBWBVQfv67Fj6GwkL4vzw85M5hifPAE6M"
[programs.mainnet]
switchboard_vrf_flip = "4TXz5v1tmgSXBWBVQfv67Fj6GwkL4vzw85M5hifPAE6M"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha --extension ts --require ts-node/register -t 1000000 tests/**/*.test.ts"
